In [41]:
import sys
import pandas as pd
import numpy as np
import datetime as dt
import glob 

# 프로젝트 루트 직접 지정
sys.path.insert(0, r"C:\airflow")

# 코드

In [42]:
# E:\down\업로드_temp\리뷰VOC분석* glob해서 df로 읽어오기
file_list = glob.glob(r"E:\down\업로드_temp\리뷰VOC분석*.xlsx")
df_list = []
for file in file_list:
    df_temp = pd.read_excel(file, header=6)
    df_list.append(df_temp)
df = pd.concat(df_list, ignore_index=True)
df.drop_duplicates(inplace=True)
df = df[df["감정수준"] == "부정"]

In [43]:
df = df.copy()
df

,번호,매장명,매장 태그,오픈일,매장 주소,작성일자,별점,작성자,토픽,채널,...,리뷰내용,답글,답변 상태,주문메뉴,배달리뷰&키워드리뷰,이미지 URL,이미지 URL.1,이미지 URL.2,이미지 URL.3,이미지 URL.4
69,7776,법흥리점,#홀,NaN,경기도 파주시 탄현면 약산로 74,2025-06-30,5.0,요따만,레시피 준수,배달의민족,...,맛있게 잘 먹었습니다. 먹느라 사진을 못 찍었네요. 밥도 비벼서 잘 먹었는데 한가지...,"닭도리탕 전문 도리당 법흥리점을 주문해주셔서 정말 감사합니다. \n요따만님, 소중...",답변완료,[밥도둑] 낙곱새 전골,[좋아요],NaN,NaN,NaN,NaN,NaN
146,7699,충주역점,NaN,NaN,충청북도 충주시 봉방9길 4,2025-06-30,5.0,안경만두,메뉴 누락,배달의민족,...,밥이 안 왔어요ㅜㅜ,"안경만두님, 소중한 주문과 리뷰 진심으로 감사드립니다🥰 언제나 초심잃지 않으며 고객...",답변완료,1인 순살 닭도리탕 (밥포함),[좋아요],NaN,NaN,NaN,NaN,NaN
195,7650,대전둔산점,NaN,NaN,대전 서구 둔산동 1352,2025-06-30,5.0,맛품평,배달 경험,배달의민족,...,늘 지각이네요ㅋ 늘 변함없는 맛인데 어제껀 정말 예술이엇네요 쵝오엿어요 끝내주게 잘...,"맛품평님, 맛난 음식 생각나실 땐 언제나 저희 매장 찾아주세요!\n\n언제 찾아주셔...",답변완료,도리당 닭도리탕,[좋아요],https://bmreview.cdn.baemin.com/bmreview-qh2e/...,NaN,NaN,NaN,NaN
199,7646,대전장대점,NaN,NaN,대전 유성구 장대동 284-8,2025-06-30,4.0,먹는게행복한여자,음식 내 이물질,배달의민족,...,받자마자 열기전 뚜껑속 머리카락이..ㅜ\n양은 많았어요,NaN,미답변,1인 순살 닭도리탕 (밥포함),[좋아요],https://bmreview.cdn.baemin.com/bmreview-qh2e/...,https://bmreview.cdn.baemin.com/bmreview-qh2e/...,NaN,NaN,NaN
265,7580,행신점,NaN,NaN,경기도 고양시 덕양구 중앙로557번길 7-23,2025-06-30,4.0,아저시,메뉴 누락,배달의민족,...,통가래떡 왜안들어가있나요..... 하 ................리뷰보니 누락 좀...,아저시님 저희 닭도리탕 전문 도리당 행신점 찾아주셔서 감사합니다🙌 시간 내셔서 리뷰...,답변완료,1인 순살 닭도리탕 (밥포함),[좋아요],NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
142123,143,대전용전점,NaN,NaN,대전 광역시 동구 계족로 479,2026-02-25,5.0,귀라백작,배달 경험,배달의민족,...,음식은 맛있습니다\n다만 자주 시킬거 같은데 오늘 배달온 사람한테 주지 마세요 집은...,NaN,미답변,[집밥같은] 도리당 닭도리탕,"[요청사항 불이행], [다른 주소에 도착], [아쉬워요]",NaN,NaN,NaN,NaN,NaN
142147,119,서울대입구역점,NaN,NaN,서울특별시 관악구 쑥고개로 67,2026-02-25,4.0,빵빠레딸기맛,요청사항 준수여부,배달의민족,...,음식은 맛있게 먹었으나 치킨무를 받는대신\n파김치 추가1500원 있길래 추가했어요\...,NaN,미답변,[집밥같은] 도리당 닭도리탕,[좋아요],https://bmreview.cdn.baemin.com/bmreview-qh2e/...,NaN,NaN,NaN,NaN
142217,49,미사점,NaN,NaN,경기도 하남시 조정대로 150,2026-02-25,5.0,채채,온도,배달의민족,...,리뷰 쓴다고 사진까지 찍어놓고 이제서야 올리네용!! \n집 가는 시간 맞춰서 미리 ...,NaN,미답변,[한우 대창] 한우 순살 곱도리탕,[좋아요],https://bmreview.cdn.baemin.com/bmreview-qh2e/...,NaN,NaN,NaN,NaN
142253,13,양주옥정점,NaN,NaN,경기도 양주시 옥정동로5길 17,2026-02-25,5.0,캠핑가는밥솥,재료 신선도,배달의민족,...,맛있어요~!! 누룽지 백숙도\n구수하니 좋아요.\n육수도 많이 주셔서 감사해용~♡\...,NaN,미답변,[집밥같은] 도리당 닭도리탕||[삼계탕] 누룽지 닭한마리,[좋아요],NaN,NaN,NaN,NaN,NaN
142255,11,역삼점,#나홀로,NaN,서울 강남구 봉은사로30길 68,2026-02-25,3.0,냠냠,레시피 준수,배달의민족,...,고기가.. 안익은게 있어요 질겨서 먹다 뱉엇는데 안익엇더라구요,NaN,미답변,도리당 닭도리탕,[좋아요],NaN,NaN,NaN,NaN,NaN

In [44]:
df = df[df["감정수준"] == "부정"]

In [45]:
# 일자/매장별 부정수 집계
df = df.groupby(["작성일자", "매장명"], as_index=False).size().rename(columns={"size": "부정수"})

# rolling 전에 매장별 날짜 정렬 필수
df = df.sort_values(["매장명", "작성일자"]).reset_index(drop=True)

df

            작성일자    매장명  부정수
0     2025-06-20    가락점    1
1     2025-06-27    가락점    1
2     2025-07-01    가락점    1
3     2025-07-06    가락점    1
4     2025-07-07    가락점    1
...          ...    ...  ...
3353  2026-01-30  화성봉담점    1
3354  2026-02-07  화성봉담점    1
3355  2026-02-10  화성봉담점    1
3356  2026-02-21  화성봉담점    2
3357  2026-02-22  화성봉담점    3

[3358 rows x 3 columns]

In [48]:
# --- 30일 합계 계산 ---
# 최근 30일 합계
df['sum_30d_recent'] = df.groupby('매장명')['부정수'].transform(
    lambda x: x.rolling(window=30, min_periods=1).sum()
).astype(int)

# 이전 30일 합계 (31~60일 전)
df['sum_30d_prev'] = df.groupby('매장명')['부정수'].transform(
    lambda x: x.shift(30).rolling(window=30, min_periods=1).sum()
).fillna(0).astype(int)

df['pct_change_30d'] = (df['sum_30d_recent'] - df['sum_30d_prev']) / df['sum_30d_prev'].replace(0, np.nan) * 100

In [ ]:
# today변수선언 str로 
today = dt.datetime.now().strftime("%Y-%m-%d")
df = df[df["작성일자"] == today]
df = df[df["sum_30d_recent"] < df["sum_30d_prev"]]

In [13]:
df = df[df["감정수준"] == "부정"]
df.groupby(["작성일자", "매장명", "토픽"]).size().reset_index(name="부정수")

           작성일자     매장명        토픽  부정수
0    2025-10-01     강동점     고객 응대    1
1    2025-10-01     강동점  음식 내 이물질    1
2    2025-10-01  구로디지털점     메뉴 누락    1
3    2025-10-01   구리다산점         맛    1
4    2025-10-01   김포장기점         양    1
..          ...     ...       ...  ...
679  2025-10-31   평택비전점         맛    1
680  2025-10-31   평택서정점         맛    1
681  2025-10-31   화성봉담점    레시피 준수    1
682  2025-10-31   화성봉담점         맛    1
683  2025-10-31   화성봉담점     메뉴 구성    1

[684 rows x 4 columns]