In [1]:
import sys
import pandas as pd
import numpy as np
import datetime as dt
import glob 

# 프로젝트 루트 직접 지정
sys.path.insert(0, r"C:\airflow")

# 코드

In [11]:
import duckdb

path = r"c:/Users/민준/OneDrive - 주식회사 도리당/data/mart/unified_sales_grp/unified_sales_*"

query = f"""
WITH temp_01 AS (
    SELECT DISTINCT order_id
    FROM read_parquet('{path}')
    WHERE item_name LIKE '%땡초%'
)

SELECT *
FROM read_parquet('{path}')
WHERE order_id IN (
    SELECT order_id
    FROM temp_01
)
ORDER BY sale_date, order_id
"""

df_review_order = duckdb.query(query).to_df()

df_review_order

,sale_date,ym,source,brand,store,region,담당자,실오픈일,platform,order_type,...,item_id,item_name,qty,unit_price,total_price,discount_amount,sale_type,_pk,collected_at,order_cnt
0,2026-03-21,2026-03,posfeed,도리당,창원내서점,경상,이병두 과장,2025-11-27,땡겨요,배달,...,81d78354c7c078feabf63a461673bf05,기본,1,21000,21000,0,정상,6b9ebbf5bc473c7cdb359e141bb92411,2026-05-15 04:51:32,1
1,2026-03-21,2026-03,posfeed,도리당,창원내서점,경상,이병두 과장,2025-11-27,땡겨요,배달,...,24b0d82f0fbbfa7e3ed99c907160392b,떡사리10개,1,1000,1000,0,정상,120463ed38d6f57ce1d6532e8d9986b7,2026-05-15 04:51:32,0
2,2026-03-21,2026-03,posfeed,도리당,창원내서점,경상,이병두 과장,2025-11-27,땡겨요,배달,...,65043276a336c55a41444a399b08b124,땡초양념,1,500,500,0,정상,504e5e3deb2eaf7f3fc6a370e489a285,2026-05-15 04:51:32,0
3,2026-03-21,2026-03,posfeed,도리당,창원내서점,경상,이병두 과장,2025-11-27,땡겨요,배달,...,f01b4ad86e4589571f60502d6f360a16,배달비,1,2000,2000,0,정상,a962878a84361256e58a7cc8d42fc382,2026-05-15 04:51:32,0

In [ ]:
import duckdb

path = r"c:/Users/민준/OneDrive - 주식회사 도리당/data/mart/unified_sales_grp/unified_sales_*"

query = f"""
WITH temp_01 AS (
    SELECT DISTINCT order_id
    FROM read_parquet('{path}')
)

SELECT *
FROM read_parquet('{path}')
WHERE order_id IN (
    SELECT order_id
    FROM temp_01
)

ORDER BY sale_date, order_id
"""

df_review_order = duckdb.query(query).to_df()

df_review_order

,sale_date,ym,source,brand,store,region,담당자,실오픈일,platform,order_type,...,item_id,item_name,qty,unit_price,total_price,discount_amount,sale_type,_pk,collected_at,order_cnt
0,2026-01-01,2026-01,easypos,도리당,송파점,서울,이병두 과장,2023-09-08,홀,홀_테이블,...,54,누룽지닭한마리,1,29500,29500,0,정상,e4e79b133217652323bb19493d95f7ae,2026-05-14 01:45:00,1
1,2026-01-01,2026-01,easypos,도리당,송파점,서울,이병두 과장,2023-09-08,홀,홀_테이블,...,49,청하,4,24000,24000,0,정상,ff15cfa7b1144d1f2c461a5e3c258cf5,2026-05-14 01:45:00,0
2,2026-01-01,2026-01,easypos,도리당,송파점,서울,이병두 과장,2023-09-08,홀,홀_테이블,...,38,맥주,3,15000,15000,0,정상,0ac7bf2ca29eac1f5089a74928f0f060,2026-05-14 01:45:00,0
3,2026-01-01,2026-01,easypos,도리당,송파점,서울,이병두 과장,2023-09-08,홀,홀_테이블,...,39,음료,1,2000,2000,0,정상,f6c752be0f1316731696420442355654,2026-05-14 01:45:00,0
4,2026-01-01,2026-01,easypos,도리당,송파점,서울,이병두 과장,2023-09-08,홀,홀_테이블,...,18,볶음밥,1,4000,4000,0,정상,749ce0e080b8c13fe8f00e121e43e0b9,2026-05-14 01:45:00,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1792567,2026-05-14,2026-05,okpos,도리당,동두천지행점,경기,황대성 대리,2025-11-20,쿠팡이츠,배달,...,10000686,+미니계란찜,1,2000,2000,0,정상,d09ee0badfa152214c947bcd42ed6775,2026-05-15 00:47:21,1
1792568,2026-05-14,2026-05,okpos,도리당,송파삼전점,서울,심성준 이사,2026-04-17,홀,홀_테이블,...,10000799,닭도리 정식(2인)(밥포함),1,24000,24000,0,정상,da28758a0ce6db9a3feeb192952f897d,2026-05-15 00:47:21,0
1792569,2026-05-14,2026-05,okpos,도리당,송파삼전점,서울,심성준 이사,2026-04-17,홀,홀_테이블,...,10000806,카스 500ml,2,5000,10000,0,정상,eb5c96ae7ac93448157dab2f790c0f0c,2026-05-15 00:47:21,0
1792570,2026-05-14,2026-05,okpos,도리당,송파삼전점,서울,심성준 이사,2026-04-17,홀,홀_테이블,...,10000861,야채S(팽이버섯+미나리),1,4900,4900,0,정상,b1a8a85484248333f93084df939808a8,2026-05-15 00:47:21,0
1792571,2026-05-14,2026-05,okpos,도리당,송파삼전점,서울,심성준 이사,2026-04-17,홀,홀_테이블,...,10000914,공기밥 추가,3,0,0,0,정상,e18a0d210c54f668be9ca21604415624,2026-05-15 00:47:21,1